version: '2'
services:
    # cargo:
    #     build: docker/cargo
    #     volumes:
    #         - .:/code
    nodewebpack:
        build: docker/node
        volumes:
            - ..:/code
    nginx:
        build: docker/nginx
        volumes: 
            - ..:/usr/share/nginx/html:ro
        ports:
            - 8080:80
